### PR TITLE
Fix Xcode 15 compiler error related to @available on stored properties

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by stevelandeyasana** [comment]
I did something similar on our fork, and also addressed the warnings: https://github.com/Asana/FittedSheets/pull/3

**Comment by AndrewSB** [comment]
ahh cool! you're keeping an upto-date fork. love it, i might have my app target that instead

@gordontucker we want to put no pressure on you, but i'm sure either @stevelandeyasana or i would be happy to help take on the burden of maintaining this repo

**Comment by Bjornftw** [comment]
If you're using CocoaPods and want to use FittedSheets on Xcode 15:
`pod 'FittedSheets', :git => 'https://github.com/AndrewSB/FittedSheets.git', :branch => 'xcode-15'`

**Comment by ThomasGoehringer** [comment]
Is there any news on when this will be merged? @gordontucker

**Pull request merged**
